jobs:

- job: linux_python37_sdist
  pool:
    vmImage: ubuntu-16.04
  variables:
    interpreter: python3.7
    target: x86_64-unknown-linux-gnu
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.7'
      addToPath: true
  - checkout: self
  - template: ./azure-linux.yml
    parameters:
      dependencies: apt
  - template: ./azure-sdist.yml

- job: manylinux1_python38
  pool:
    vmImage: ubuntu-16.04
  container: aviramhassan/manylinux1_gcc:x86_64
  variables:
    interpreter: /opt/python/cp38-cp38/bin/python3.8
    manylinux: 1
    path: /opt/python/cp38-cp38/bin:/opt/python/cp38-cp38/lib:/home/vsts_azpcontainer/.local/bin:/home/vsts_azpcontainer/.cargo/bin:/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    target: x86_64-unknown-linux-gnu
  steps:
  - checkout: self
  - template: ./azure-linux.yml
    parameters:
      dependencies: apt
  - template: ./azure-posix.yml

- job: manylinux1_python37
  pool:
    vmImage: ubuntu-16.04
  container: aviramhassan/manylinux1_gcc:x86_64
  variables:
    interpreter: /opt/python/cp37-cp37m/bin/python3.7
    manylinux: 1
    target: x86_64-unknown-linux-gnu
    path: /opt/python/cp37-cp37m/bin:/opt/python/cp37-cp37m/lib:/home/vsts_azpcontainer/.local/bin:/home/vsts_azpcontainer/.cargo/bin:/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
  steps:
  - checkout: self
  - template: ./azure-linux.yml
    parameters:
      dependencies: apt
  - template: ./azure-posix.yml

- job: manylinux1_python36
  pool:
    vmImage: ubuntu-16.04
  container: aviramhassan/manylinux1_gcc:x86_64
  variables:
    interpreter: /opt/python/cp36-cp36m/bin/python3.6
    manylinux: 1
    target: x86_64-unknown-linux-gnu
    path: /opt/python/cp36-cp36m/bin:/opt/python/cp36-cp36m/lib:/home/vsts_azpcontainer/.local/bin:/home/vsts_azpcontainer/.cargo/bin:/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
  steps:
  - checkout: self
  - template: ./azure-linux.yml
    parameters:
      dependencies: apt
  - template: ./azure-posix.yml

- job: macos_python38
  pool:
    vmImage: xcode9-macos10.13
  variables:
    interpreter: python3.8
    manylinux: off
    target: x86_64-apple-darwin
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.8'
      addToPath: true
  - checkout: self
  - template: ./azure-macos.yml

- job: macos_python37
  pool:
    vmImage: xcode9-macos10.13
  variables:
    interpreter: python3.7
    manylinux: off
    target: x86_64-apple-darwin
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.7'
      addToPath: true
  - checkout: self
  - template: ./azure-macos.yml

- job: macos_python36
  pool:
    vmImage: xcode9-macos10.13
  variables:
    interpreter: python3.6
    manylinux: off
    target: x86_64-apple-darwin
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.6'
      addToPath: true
  - checkout: self
  - template: ./azure-macos.yml
